export const HIRAGANA = 'Hiragana'
export const KATAKANA = 'Katakana'
export const NUMBERS = 'Numbers'
export const DATES = 'Dates'
export const TIME = 'Time'
export const COUNTERS = 'Counters'
export const KANA = 'Kana'

export const ENABLED = 'Enabled'
export const PLAY = 'Play'
