// constants
export const HIRAGANA = 'Hiragana'
export const KATAKANA = 'Katakana'
export const NUMBERS = 'Numbers'
export const DATES = 'Dates'
export const TIME = 'Time'
export const COUNTERS = 'Counters'
export const KANA = 'Kana'
export const TEXT = 'Text'
export const SOUND = 'Sound'
export const ROMAJI = 'Romaji'
// getters
export const ENABLED = 'Enabled'
export const SETTINGS = 'Settings'
export const CURRENT_GAME = 'CurrentGame'
export const ONGOING = 'Ongoing'
export const CURRENT_ROUND = 'CurrentRound'
export const QUESTION = 'Question'
export const POSSIBILITIES = 'Possibilities'
export const ATTEMPTED_ANSWERS = 'attemptedAnswers'
export const HAS_BEEN_ATTEMPTED = 'hasBeenAttempted'
export const CURRENT_ROUND_GAME_MODE = 'currentRoundGameMode'
export const RESULTS = 'Results'
export const PROGRESS = 'Progess'
export const FINISHED = 'Finished'
// actions and mutations
export const PLAY = 'Play'
export const START = 'Start'
export const CONTINUE = 'Continue'
export const ANSWER = 'Answer'
export const FINISH = 'Finish'
