import { KANA, ROMAJI, TEXT, SOUND } from '../constants'

export const NAMESPACE = 'hiragana'
export const RANDOM = 'Random'

export const GAME_MODES = [
  { id: 'HiraganaToRomaji', text: 'Hiragana to Romaji', question: KANA, answer: ROMAJI, type: TEXT },
  { id: 'SoundToHiragana', text: 'Sound to Hiragana', question: KANA, answer: KANA, type: SOUND },
  { id: 'RomajiToHiragana', text: 'Romaji to Hiragana', question: ROMAJI, answer: KANA, type: TEXT },
  { id: RANDOM, text: 'Random' }
]

export const SYMBOLS = [
  { Romaji: 'a', Kana: 'あ' },
  { Romaji: 'i', Kana: 'い' },
  { Romaji: 'u', Kana: 'う' },
  { Romaji: 'e', Kana: 'え' },
  { Romaji: 'o', Kana: 'お' },
  { Romaji: 'ka', Kana: 'か' },
  { Romaji: 'ki', Kana: 'き' },
  { Romaji: 'ku', Kana: 'く' },
  { Romaji: 'ke', Kana: 'け' },
  { Romaji: 'ko', Kana: 'こ' },
  { Romaji: 'ga', Kana: 'が' },
  { Romaji: 'gi', Kana: 'ぎ' },
  { Romaji: 'gu', Kana: 'ぐ' },
  { Romaji: 'ge', Kana: 'げ' },
  { Romaji: 'go', Kana: 'ご' },
  { Romaji: 'sa', Kana: 'さ' },
  { Romaji: 'shi', Kana: 'し' },
  { Romaji: 'su', Kana: 'す' },
  { Romaji: 'se', Kana: 'せ' },
  { Romaji: 'so', Kana: 'そ' },
  { Romaji: 'za', Kana: 'ざ' },
  { Romaji: 'ji', Kana: 'じ' },
  { Romaji: 'zu', Kana: 'ず' },
  { Romaji: 'ze', Kana: 'ぜ' },
  { Romaji: 'zo', Kana: 'ぞ' },
  { Romaji: 'ta', Kana: 'た' },
  { Romaji: 'chi', Kana: 'ち' },
  { Romaji: 'tsu', Kana: 'つ' },
  { Romaji: 'te', Kana: 'て' },
  { Romaji: 'to', Kana: 'と' },
  { Romaji: 'da', Kana: 'だ' },
  { Romaji: 'ji', Kana: 'ぢ' },
  { Romaji: 'zu', Kana: 'づ' },
  { Romaji: 'de', Kana: 'で' },
  { Romaji: 'do', Kana: 'ど' },
  { Romaji: 'na', Kana: 'な' },
  { Romaji: 'ni', Kana: 'に' },
  { Romaji: 'nu', Kana: 'ぬ' },
  { Romaji: 'ne', Kana: 'ね' },
  { Romaji: 'no', Kana: 'の' },
  { Romaji: 'ha', Kana: 'は' },
  { Romaji: 'hi', Kana: 'ひ' },
  { Romaji: 'fu', Kana: 'ふ' },
  { Romaji: 'he', Kana: 'へ' },
  { Romaji: 'ho', Kana: 'ほ' },
  { Romaji: 'ba', Kana: 'ば' },
  { Romaji: 'bi', Kana: 'び' },
  { Romaji: 'bu', Kana: 'ぶ' },
  { Romaji: 'be', Kana: 'べ' },
  { Romaji: 'bo', Kana: 'ぼ' },
  { Romaji: 'pa', Kana: 'ぱ' },
  { Romaji: 'pi', Kana: 'ぴ' },
  { Romaji: 'pu', Kana: 'ぷ' },
  { Romaji: 'pe', Kana: 'ぺ' },
  { Romaji: 'po', Kana: 'ぽ' },
  { Romaji: 'ma', Kana: 'ま' },
  { Romaji: 'mi', Kana: 'み' },
  { Romaji: 'mu', Kana: 'む' },
  { Romaji: 'me', Kana: 'め' },
  { Romaji: 'mo', Kana: 'も' },
  { Romaji: 'ya', Kana: 'や' },
  { Romaji: 'yu', Kana: 'ゆ' },
  { Romaji: 'yo', Kana: 'よ' },
  { Romaji: 'ra', Kana: 'ら' },
  { Romaji: 'ri', Kana: 'り' },
  { Romaji: 'ru', Kana: 'る' },
  { Romaji: 're', Kana: 'れ' },
  { Romaji: 'ro', Kana: 'ろ' },
  { Romaji: 'wa', Kana: 'わ' },
  { Romaji: 'wo', Kana: 'を' },
  { Romaji: 'n', Kana: 'ん' },
  { Romaji: 'kya', Kana: 'きゃ' },
  { Romaji: 'kyu', Kana: 'きゅ' },
  { Romaji: 'kyo', Kana: 'きょ' },
  { Romaji: 'gya', Kana: 'ぎゃ' },
  { Romaji: 'gyu', Kana: 'ぎゅ' },
  { Romaji: 'gyo', Kana: 'ぎょ' },
  { Romaji: 'sha', Kana: 'しゃ' },
  { Romaji: 'shu', Kana: 'しゅ' },
  { Romaji: 'sho', Kana: 'しょ' },
  { Romaji: 'ja', Kana: 'じゃ' },
  { Romaji: 'ju', Kana: 'じゅ' },
  { Romaji: 'jo', Kana: 'じょ' },
  { Romaji: 'cha', Kana: 'ちょ' },
  { Romaji: 'chu', Kana: 'ちゅ' },
  { Romaji: 'cho', Kana: 'ちょ' },
  { Romaji: 'nya', Kana: 'にゃ' },
  { Romaji: 'nyu', Kana: 'にゅ' },
  { Romaji: 'nyo', Kana: 'にょ' },
  { Romaji: 'hya', Kana: 'ひゃ' },
  { Romaji: 'hyu', Kana: 'ひゅ' },
  { Romaji: 'hyo', Kana: 'ひょ' },
  { Romaji: 'bya', Kana: 'びゃ' },
  { Romaji: 'byu', Kana: 'びゅ' },
  { Romaji: 'byo', Kana: 'びょ' },
  { Romaji: 'pya', Kana: 'ぴゃ' },
  { Romaji: 'pyu', Kana: 'ぴゅ' },
  { Romaji: 'pyo', Kana: 'ぴょ' },
  { Romaji: 'mya', Kana: 'みゃ' },
  { Romaji: 'myu', Kana: 'みゅ' },
  { Romaji: 'myo', Kana: 'みょ' },
  { Romaji: 'rya', Kana: 'りゃ' },
  { Romaji: 'ryu', Kana: 'りゅ' },
  { Romaji: 'ryo', Kana: 'りょ' }
]
